### ISSUE TITLE
Source code not generated

### ISSUE THREAD

**Issue by markushaslinger** [nenoNaninu/TypedSignalR.Client#121]
Want to use this nice library, but do receive the following error `TypedSignalR.Client did not generate source code to create a hub proxy, which type is MyNamespace.ITestHub`.

I tried to follow the instructions, my simple usage:

```csharp
var url = new Uri(_settings.BackendUri, hubRoute);
var hubConnection = new HubConnectionBuilder()
   .WithUrl(url, options =>
   {
       options.AccessTokenProvider = async () =>
       {
           var tokenProvider = serviceProvider.GetRequiredService<IAccessTokenProvider>();
           var tokenResult = await tokenProvider.RequestAccessToken();
           if (tokenResult.TryGetToken(out var token))
           {
               return token.Value;
           }  
           throw new InvalidOperationException("Access token not available");
       };
   })
   .WithAutomaticReconnect()
   .Build();
await hubConnection.StartAsync();
var hub = hubConnection.Connection.CreateHubProxy<ITestHub>(); // <-- Exception here
var subscription = hubConnection.Connection.Register<ITestHubClient>(this);
```

The interface is totally basic:

```csharp
public interface ITestHub
{
    public Task SendMessage(TestMessage message);
}
```

Would appreciate some pointers on what I'm doing wrong here.

**Comment by nenoNaninu** [comment]
What is 'hubConnection.Connection'?

Please use `Microsoft.AspNetCore.SignalR.Client` as the SignalR client package. And **no** `Connection` property is in the `HubConnection` class included in that package.

If you use "Microsoft.AspNetCore.SignalR.Client", you can fix it as follows.

```cs
var hub = hubConnection.CreateHubProxy<ITestHub>();
var subscription = hubConnection.Register<ITestHubClient>(this);
```

**Comment by markushaslinger** [comment]
> What is `hubConnection.Connection`?

I'm sorry, that was just a typo.

> Please use `Microsoft.AspNetCore.SignalR.Client` as the SignalR client package. And **no** `Connection` property is in the `HubConnection` class included in that package.

I am using `Microsoft.AspNetCore.SignalR.Client`.
I have [created a MWE project](https://github.com/markushaslinger/signalr-typed_repro_no-code-generated) for you with most of the complexity stripped away but the core configuration remaining which exhibits the issue ([Exception thrown when attempting to access the hub proxy](https://github.com/markushaslinger/signalr-typed_repro_no-code-generated/blob/master/Client/Pages/Index.razor#L33)). I hope this helps you to understand what I am doing.

Thanks for your support!

**Comment by nenoNaninu** [comment]
The limitation is that the source generator does not analyze the code block in the `.razor` file. `CreateHubProxy` / `Register` should be written in the `.cs` file, not in the `.razor` file.

See the issue comment below for details.
https://github.com/nenoNaninu/TypedSignalR.Client/issues/110#issuecomment-1585472944

**Comment by markushaslinger** [comment]
Ah! I was putting it in there to keep things simple while testing and shot myself in the foot by doing so...
You are right, I never made the connection with the razor file and didn't look at the issue you mentioned.

My bad, it's working now. Thanks again for the help!
