### ISSUE TITLE
Escaped reserved identifiers cause issues in generated code

### ISSUE THREAD

**Issue by zorgoz** [nenoNaninu/TypedSignalR.Client#161]
Great job there! Thanks for your effort.
One remark though: I have spent quite a lot of time to figure out why the generated code is full with strange errors, while I have followed the instructions you gave. It turned out that the generator could not handle my method parameter with the name `@event`. The generated code stripped the monkey, which resulted in quite a mess.

![image](https://github.com/nenoNaninu/TypedSignalR.Client/assets/1569170/20e3f96d-da75-4e4f-8933-b3bba40199fd)

**Comment by nenoNaninu** [comment]
Thanks for reporting the issue. I fixed this issue and released v3.4.3. Try it!

**Comment by zorgoz** [comment]
Thank you, it is working now!
