### ISSUE TITLE
Add ClientFactory Functionality

### ISSUE THREAD

**Issue by bbunderson** [nenoNaninu/TypedSignalR.Client#166]
I think adding ClientFactory functionality would be really helpful. Similar to how IHttpClientFactory can be used. The client could then be injected into the Program.cs and accessed via DI throughout the app. I have been trying to find how to manually inject the HubConnection on the client side. I would be happy to collaborate on something like this. I believe that SignalR is held back by it's client api. 

Similar to this:
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-8.0
And how Refit does for HttpClients.

**Comment by nenoNaninu** [comment]
It would be easy to provide APIs similar to HttpClientFactory, such as HubConnectionFactory. But it makes no sense.
HttpClientFactory has many features, such as efficient socket management and support for DNS changes. But what does HubConnectionFactory want to manage? How you want to manage HubConnection in DI is different for each application.

In conclusion, TypedSignalR.Client does not plan to provide APIs like HttpClientFactory.
