### ISSUE TITLE
Usage in Unity

### ISSUE THREAD

**Issue by biosmanager** [nenoNaninu/TypedSignalR.Client#175]
We are trying to use this in a Unity project. We are importing the DLL like this:
https://docs.unity3d.com/Manual/roslyn-analyzers.html

However, Unity complains that it cannot find the namespace and types contained in the TypedSignalR.Client.dll.
Do you have any suggestions on how to use it with Unity?

We also tried to manually add the DLL to the C# compiler (csc.rsp) but also no luck there.

**Comment by nenoNaninu** [comment]
TypedSignalR.Client uses Roslyn v4.4.0. I don't know what version of Unity is available for Roslyn v4.4.0. Please try it with the latest Unity version, 2023.2.

**Comment by biosmanager** [comment]
I tried it with the latest Unity version 2023.2.7. Appears that it still uses v4.3.0:
```
warning CS9057: The analyzer assembly 'D:\Repos\PostureControlLab\Balance XR\Anaropia\anaropia\anaropia-unity\Assets\Packages\TypedSignalR.Client.3.4.3\analyzers\dotnet\cs\TypedSignalR.Client.dll' references version '4.4.0.0' of the compiler, which is newer than the currently running version '4.3.0.0'.
```

How could I modify TypedSignalR.Client to "downgrade" to 4.3.0?

**Comment by nenoNaninu** [comment]
Fix [Directory.Packages.props#L10](https://github.com/nenoNaninu/TypedSignalR.Client/blob/master/Directory.Packages.props#L10) and build.

**Comment by biosmanager** [comment]
This certainly helped to get further. However, now I have the following problem:

```
TypedSignalR.Client\TypedSignalR.Client.SourceGenerator\TypedSignalR.Client.Components.Generated.cs(34,59): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)
```
However, I have the `Microsoft.AspNetCore.SignalR.Client` package installed using NuGet for Unity.
What is the problem here?

**Comment by nenoNaninu** [comment]
Can you use classes such as HubConnection in your own code?

**Comment by biosmanager** [comment]
Yeah, so that's the strange thing. It works in my own code but apparently not in the generated code.

**Comment by biosmanager** [comment]
I think I solved it by referencing the SignalR DLLs in Unity:

![image](https://github.com/nenoNaninu/TypedSignalR.Client/assets/9850952/1864c511-1e13-4d1a-8847-b5aaff56a319)
