### ISSUE TITLE
Nullable as parameter gives CS8639

### ISSUE THREAD

**Issue by rogerjak** [nenoNaninu/TypedSignalR.Client#195]
Thanks for fixing nullables as return value.
But I also have nullables as parameters, and now with 3.5.0 I get a compile error instead:
CS8639 The typeof operator cannot be used on a nullable reference type
So the warnings before were better than the errors now :(

**Comment by nenoNaninu** [comment]
Thanks for reporting the issue. I fixed this issue and released v3.5.1. Try it!

**Comment by rogerjak** [comment]
Tried 3.5.1 and still the same :(

**Comment by nenoNaninu** [comment]
Please upload an example code that reproduces the problem. All tests are passing.

**Comment by rogerjak** [comment]
`public interface IAdapterHubClient : IAddonHubClient
{
    Task<bool> SetValueAsync(EntityAddress entityAddress, EntityMemberId fieldId, DataWithType? newValue);
}`

The types are our own records/classes.

**Comment by nenoNaninu** [comment]
I fixed this issue and released v3.5.2. Try it!

**Comment by rogerjak** [comment]
Working in 3.5.2. Thank you!
