### ISSUE TITLE
Is Possibile to generate the java/kotlin contract codes with this project?

### ISSUE THREAD

**Issue by Zhao-Michael** [nenoNaninu/TypedSignalR.Client#241]
Just wanted to discuss feasibility, thanks~

**Comment by nenoNaninu** [comment]
This project supports only C# SignalR clients. It does not support other languages, and there are no plans to do so.

However, [TypedSignalR.Client.TypeScript](https://github.com/nenoNaninu/TypedSignalR.Client.TypeScript) achieves code generation for TypeScript SignalR clients.
