### ISSUE TITLE
Support  client results (.NET 7)

### ISSUE THREAD

**Issue by nenoNaninu** [nenoNaninu/TypedSignalR.Client#43]
[.NET Blog](https://devblogs.microsoft.com/dotnet/asp-net-core-updates-in-dotnet-7-preview-4/#client-results-in-signalr) described the following statement.

> Previously, when using SignalR, the server could invoke a method on a client but didn’t have the ability to wait for a response. This scenario is now supported with .NET 7 Preview 4. 

I would like to support this new feature when it enters the official release of .NET 7.

**Comment by szingg** [comment]
any progress on this? .NET 7 has now been released

**Comment by nenoNaninu** [comment]
I will support this feature. But currently, I don't have enough time, so it isn't easy to support it right now.

**Comment by davidfowl** [comment]
This library looks very cool! Looking forward to client result support!

**Comment by nenoNaninu** [comment]
I released `v3.2.1`. This version supports client results!
